[project]
name = "django-channels-chat"
version = "0.1.0"
description = ""
authors = [
    {name = "k.barylnikov",email = "ipt_git_bot@ipt.ru"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "asgiref (>=3.11.1,<4.0.0)",
    "django (>=6.0.3,<7.0.0)",
    "sqlparse (>=0.5.5,<0.6.0)",
    "channels (>=4.3.2,<5.0.0)",
    "daphne (>=4.2.1,<5.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
format.preview = true  # To enable quote-style preserve
format.quote-style = 'preserve'

[dependency-groups]
dev = [
    "ruff (>=0.15.7,<0.16.0)"
]
